# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: romcleaner

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################

  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-x86.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-arm64.yml'


  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs

# Windows 64-bit
libretro-build-windows-x86:
  extends:
    - .libretro-windows-cmake-x86
    - .core-defs

# Linux 32-bit
libretro-build-linux-x86:
  extends:
    - .libretro-linux-cmake-x86
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - sudo apt-get update -qy
    - sudo apt-get install -qy software-properties-common
    - sudo add-apt-repository -y ppa:savoury1/build-tools
    - sudo apt-get update -qy
    - sudo apt-get install -qy cmake
  # This container's existing installation of CMake is way too old

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

################################### CELLULAR #################################

# Android ARMv7a
libretro-build-android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

# Android ARMv8a
libretro-build-android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - /android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "cmake;3.30.3"
    - export PATH=/android-sdk-linux/cmake/3.30.3/bin:$PATH

# Android 32-bit x86
libretro-build-android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs

# Android 64-bit x86
libretro-build--x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - /android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "cmake;3.30.3"
    - export PATH=/android-sdk-linux/cmake/3.30.3/bin:$PATH

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs
  variables:
    CORE_ARGS: --toolchain ./cmake/toolchain/ios.toolchain.cmake -DPLATFORM=OS64

# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs
  variables:
    CORE_ARGS: --toolchain ./cmake/toolchain/ios.toolchain.cmake -DPLATFORM=TVOS
